config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :plans, only: [:index] do
    collection do
      post :remove
      post :add
      get :refresh # Routes pour le bouton Randomiser (ne pas supprimer)
      get :export # Routes pour bouton Export PDF (ne pas supprimer)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, dependent: :destroy
  has_many :recipe_tags
  has_many :tags, through: :recipe_tags
end

app/models/recipe_tag.rb
class RecipeTag < ApplicationRecord
  belongs_to :tag
  belongs_to :recipe
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :recipe_tags, dependent: :destroy

  def name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @recipes = Recipe.take(2)
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  def index
    # Affiche le menu de la semaine
    @recipes = Recipe.order('RANDOM()').limit(5)

    cookies[:plan_recipes] = []
    cookies[:nb_persons] = []
    cookies[:already_proposed] = @recipes.map(&:id).map(&:to_s).join(',')

    # bouton export (gem WickedPdf)
    @recipe = Recipe.first
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "file_name", template: "plans/index.html.erb"             # Excluding ".pdf" extension.
      end
    end
  end

  def add
    @recipe = Recipe.find(params[:recipe_id])

    # serialize / deserialize nb person
    nb_persons = cookies[:nb_persons].split(',')
    nb_persons << params[:nb_person].to_s
    cookies[:nb_persons] = nb_persons.join(',')

    plan_recipes = cookies[:plan_recipes].split(',')
    plan_recipes << @recipe.id.to_s
    ap Recipe.where(id: plan_recipes).pluck(:name)
    cookies[:plan_recipes] = plan_recipes.join(',')
    ap "je suis dans #{__method__}"
    ap cookies[:plan_recipes]
  end

  def remove
    # retrieving recipe from Ajax ex: recipe_id = 119
    @recipe = Recipe.find(params[:recipe_id])
    # converting cookies nb_persons into array ex: "4,4,5" => ["4", "4", "5"]
    nb_persons = cookies[:nb_persons].split(',')
    # converting cookies plan_recipes into array ex: "120,119,156" => ["120", "119", "156"]
    plan_recipes = cookies[:plan_recipes].split(',')
    # retriving the recipe index to remove in ["120", "119", "156"].index("119") => 1
    recipe_index_to_remove = plan_recipes.index(@recipe.id.to_s)
    # removing recipe in array plan_recipes => ["120", "156"]
    plan_recipes = plan_recipes - [@recipe.id.to_s]
    # removing quantity at the right index => ["4", "5"]
    nb_persons.delete_at(recipe_index_to_remove)

    ap Recipe.where(id: plan_recipes).pluck(:name)

    # inserting new cookies
    cookies[:plan_recipes] = plan_recipes.join(',')
    cookies[:nb_persons] = nb_persons.join(',')
  end

  def refresh

    plan_recipes = cookies[:plan_recipes].split(',')
    already_proposed = cookies[:already_proposed].split(',')
    nb = 5 - plan_recipes.length

    if params[:filter].present?
      tag = Tag.find_by(name: params[:filter])
      ap tag
    end

    new_recipes = RandomRecipes.new(already_proposed, nb, tag ||= nil ).call
    ap new_recipes
    already_proposed += new_recipes.map(&:id)
    cookies[:already_proposed] = already_proposed.map(&:to_s).join(',')
    recipe_cards = new_recipes.map do |recipe|
      render_to_string(partial: "shared/card", locals: { recipe: recipe })
    end

    data = {recipe_cards: recipe_cards}
    render json: data
  end

  # Checkboxes du Menu
  def update
  end

  # Exporter le menu en PDF
  def export
    ap "je suis dans #{__method__}"
    ap cookies[:plan_recipes]

    # desirialization des cookies
    recipes_ids = cookies[:plan_recipes].split(',').map(&:to_i)

    @nb_persons = cookies[:nb_persons].split(',').map(&:to_i)
    ap recipes_ids
    # Affiche le menu de la semaine (aléatoire avec une limite de 5)
    @recipes = Recipe.find(recipes_ids)



    # Bouton export (gem WickedPdf)
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "file_name",
        template: "plans/pdf.html.erb",                     # Fichier de template
        title: 'RandoMeal, le menu de votre semaine',       # Titre de la page
        page_size: "A4",                                    # Format de la page
        encoding: 'TEXT',
        font_name: 'Arial',                                 # Police d'écritures
        margin: {top: 12, bottom: 12, left: 15, right: 12}  # Mise en page
      end
    end
  end

  private

  # Méthode privé des Checkboxes du Menu
  def plan_params
    params.require(:tag).permit(:name)
    # params.require(:plan).permit(:name)
    # params.require(:recipe).permit(:name, :image, :url_marmiton, :price, :prep_duration, :total_duration, :people)
    # params.require(:ingredient).permit(:name, :quantity, :mesurement, :recipe_id)
  end
end

app/controllers/random_recipes_controller.rb
class RandomRecipesController < ApplicationController
  def randomize
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def ingredient_displayer(recipe, nb_person)
    results = recipe.ingredients.map do |ingredient|
      [ingredient.quantity.to_i.fdiv(recipe.people) * nb_person.to_i , ingredient.name]
    end

    results.flatten.join(" ")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<!-- ██████   █████  ███    ██ ██████   ██████  ███    ███ ███████  █████  ██       -->
<!-- ██   ██ ██   ██ ████   ██ ██   ██ ██    ██ ████  ████ ██      ██   ██ ██       -->
<!-- ██████  ███████ ██ ██  ██ ██   ██ ██    ██ ██ ████ ██ █████   ███████ ██       -->
<!-- ██   ██ ██   ██ ██  ██ ██ ██   ██ ██    ██ ██  ██  ██ ██      ██   ██ ██       -->
<!-- ██   ██ ██   ██ ██   ████ ██████   ██████  ██      ██ ███████ ██   ██ ███████  -->

<html>
  <head>
    <!-- Primary Meta Tags -->
    <title>Randomeal - Planifier, générer et organiser vos repas de la semaine en seulement quelques clics</title>
    <meta name="title" content="Randomeal - Planifier, générer et organiser vos repas de la semaine en seulement quelques clics">
    <meta name="description" content="Avec Randomeal, gagner du temps et de l'argent avec vos repas ! Planifier, générer et organiser vos repas de la semaine en seulement quelques clics">
    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="http://www.randomeal.xyz">
    <meta property="og:title" content="Randomeal - Planifier, générer et organiser vos repas de la semaine en seulement quelques clics">
    <meta property="og:description" content="Avec Randomeal, gagner du temps et de l'argent avec vos repas ! Planifier, générer et organiser vos repas de la semaine en seulement quelques clics">
    <meta property="og:image" content="http://www.randomeal.xyz/images/assets/randomeal_socialsizes.png">
    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="http://www.randomeal.xyz">
    <meta property="twitter:title" content="Randomeal - Planifier, générer et organiser vos repas de la semaine en seulement quelques clics">
    <meta property="twitter:description" content="Avec Randomeal, gagner du temps et de l'argent avec vos repas ! Planifier, générer et organiser vos repas de la semaine en seulement quelques clics">
    <meta property="twitter:image" content="http://www.randomeal.xyz/images/assets/randomeal_socialsizes.png">
    <!-- Responsive -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Favicon -->
    <%= favicon_link_tag %>
    <!-- UTF-8 because we are French ! -->
    <meta charset="utf-8">
    <!-- wicked_pdf helpers -->
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <!-- CSS -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- JS -->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <script src="https://kit.fontawesome.com/3c8862fa8a.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div>
      <%= yield %>
    </div>
  </body>
  <%= render 'shared/footer' %>
</html>

app/views/pages/home.html.erb
<div class="wrapper" id="top">
  <div id="scroll_to_top">
    <%= link_to '#top' do %>
      <i class="fas fa-chevron-up scroll_to_top"></i>
    <% end %>
  </div>

  <div class="home-banner">
    <div class="home-banner--logo">
      <%= image_tag "logo_randomeal_ntypo.png", class: "home-banner--logo__img" %>
      <span class="home-banner--logo__title">Randomeal</span>
    </div>
    <div class="home-banner--content">
      <h1 class="home-banner--content__title">Gagner du temps et de l'argent avec vos repas !</h1>
      <p class="home-banner--content__paragraph">Planifier, générer et organiser vos repas de la semaine en seulement quelques clics</p>
    </div>
    <%= link_to "Découvrir maintenant !", plans_path, class: "btn btn--primary" %>
  </div>

   <div class="home-feature-1">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-12 col-lg-6">
          <div class="row">
            <% @recipes.each do |recipe| %>
              <div class="col-12 col-md-6">
                <div class="card-recipe">
                  <div class="card-recipe--top">
                    <%= image_tag recipe.image, class: "card-recipe--top__img" %>
                  </div>
                  <div class="card-recipe--content">
                    <h3><%= recipe.name %></h3>
                    <p>Découvrez cette délicieuse recette de <strong><%= recipe.name %></strong> !</p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <div class="col-12 col-lg-6">
          <div class="home-feature-1--content">
            <h2>Trouvez l'inspiration</h2>
            <p>Qu'on aime la cuisine ou non, décider de ce que nous allons manger peut representer une veritable corvée... Alors laissez nous faire et régalez vous !!</p>
            <p>Filtrer vos exigences parmi nos <strong>190 235 recettes</strong>, un click et le tour est joué !
            Si le menu ne vous satisfait pas, un simple click et des nouvelles idées de recettes se présentent a vous.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="home-feature-2">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-12 col-lg-6">
          <div class="home-feature-1--content">
            <h2>Des idées de recettes pour tous les soirs de la semaine</h2>
            <p>Difficile de trouver des <strong>idées de repas à cuisiner pour tous les soirs de la semaine</strong>, surtout après une journée
            éprouvante.</p>
            <p>Avec RandoMeal, préparez et mangez des plats variés et différents chaque soir !</p>
          </div>
        </div>
        <div class="col-12 col-lg-6">
          <%= image_tag "randomeal_planificateur_de_menu.jpg" %>
        </div>
      </div>
    </div>
  </div>

  <div class="home-feature-3">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-12 col-lg-6 text-center">
          <%= image_tag "gaspillage_alimentaire.jpg" %>
        </div>
        <div class="col-12 col-lg-6">
          <div class="home-feature-1--content">
            <h2>Un geste antigaspi</h2>
            <p>Il nous est tous arrivés d'ouvrir son frigo et de devoir <strong>jeter toutes nos denrées périmées</strong>.</p>
            <p>En France, les pertes et gaspillages alimentaires représentent 10 millions de tonnes, c'est pourquoi
            en <strong>planifiant ses repas pour toute une semaine</strong>, nous pouvons tous agir contre ce fléau depuis notre cuisine. </p>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="home-feature-4">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-12 col-lg-6">
          <div class="home-feature-1--content">
            <h2>Prêt(e) à faire vos courses</h2>
            <p>En planifiant vos menus pour toute la semaine, vous saurez à l'avance ce qu'il faut acheter pendant vos courses.</p>
            <p>RandoMeal vous propose d'exportez votre <strong>liste de courses pour la semaine</strong>, avec toutes les bonnes quantités !</p>
          </div>
        </div>
        <div class="col-12 col-lg-6 text-center">
          <%= image_tag "liste_de_courses.jpg" %>
        </div>
      </div>
    </div>
  </div>

    <!-- Footer -->
  <div class="home-team">
    <div class="container">
      <div class="row">
          <h2>L'équipe RandoMeal</h2>
        <div class="col-12 col-md-4">
          <div class="home-team--container">
            <%= image_tag "charles.png" %>
            <h3>Charles</h3>
          </div>
        </div>
        <div class="col-12 col-md-4">
          <div class="home-team--container">
            <%= image_tag "deborah.jpg" %>
            <h3>Deborah</h3>
          </div>
        </div>
        <div class="col-12 col-md-4">
          <div class="home-team--container">
            <%= image_tag "pierre.png" %>
            <h3>Pierre</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/plans/index.html.erb
<div class="wrapper plan-wrap" data-controller="week" data-action="keyup@window->week#keyUp">

  <!-- Header -->
  <div class="header">
    <h1>Mes recettes de la semaine</h1>
  </div>
    <!-- Filtres des menus -->
      <div class="menu">
        <div class="preferences">
          <p class="preferences--text">Mes préférences pour cuisiner :</p>
          <div class="preferences--button btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <span class="filter" data-week-target="filter" data-filter="vegetarien" data-action="click->week#toggleActive">Végétarien</span>
            <span class="filter" data-week-target="filter" data-filter="vegan" data-action="click->week#toggleActive">Vegan</span>
            <span class="filter" data-week-target="filter" data-filter="sans gluten" data-action="click->week#toggleActive">Sans gluten</span>
            <span class="filter" data-week-target="filter" data-filter="thermomix" data-action="click->week#toggleActive">Thermomix</span>
          </div>
      </div>



      </div>



    <!-- Menu de la semaine -->
    <div class="plan-randomizer">
      <div class="row">
        <% days = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi'] %>
        <% @recipes.each_with_index do |recipe, index| %>
          <div class="col-12 col-md">
            <!-- Card des jours de la semaine -->
            <div class="day"
                data-controller="day counter"
                data-action="recipeIdChanged->day#updateRecipeIdValue lock->counter#lock unlock->counter#unlock peopleUpdated->day#peopleUpdated toggleLock->week#toggleExport toggleLock->week#remainingRecipesToUnlock"
                data-counter-people-value="<%= recipe.people %>"
                data-day-people-value="<%= recipe.people %>"
                data-week-target="day"
                data-day-recipe-id-value="<%= recipe.id %>"
                >
                <h3 class="day-name"><%= days[index] %></h3>
                <%= render 'shared/card', recipe: recipe %>
                <!-- Lock de la recette -->
                <div class="day-action" data-action="click->day#toggleLock">
                <span class="btn btn--small unlock"><i class="fas fa-unlock"></i>Je bloque</span>
                <span class="btn btn--small lock"><i class="fas fa-lock"></i>Bloqué</span>
                </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>


    <!-- Les boutons -->
    <div class="content-randomizer">
       <!-- Bouton Export -->
        <div class="wicked_pdf d-none" data-week-target="export2">

            <%= link_to export_plans_path(@recipes, :format => :pdf),  target: :blank, class: "btn btn--primary btnrand" do %>
              <i class="fas fa-download"></i> Export
            <% end %>

        </div>
        <div data-week-target="export1">
          <p class="randomizer--text">Les recettes ne te plaisent pas ? Appuie sur espace ou clique sur le bouton</p>
          <p class="block--text">Bloque encore <strong><span id="countrecipe" data-week-target="countrecipe">5</span> recette(s)</strong> pour exporter ta liste de course</p>
          <span class="btn btn--primary btnrand" data-action="click->week#randomize">RandoMiser</span>
        </div>
    </div>
</div>

app/views/plans/pdf.html.erb
<!DOCTYPE html>
<!-- ██████   █████  ███    ██ ██████   ██████  ███    ███ ███████  █████  ██       -->
<!-- ██   ██ ██   ██ ████   ██ ██   ██ ██    ██ ████  ████ ██      ██   ██ ██       -->
<!-- ██████  ███████ ██ ██  ██ ██   ██ ██    ██ ██ ████ ██ █████   ███████ ██       -->
<!-- ██   ██ ██   ██ ██  ██ ██ ██   ██ ██    ██ ██  ██  ██ ██      ██   ██ ██       -->
<!-- ██   ██ ██   ██ ██   ████ ██████   ██████  ██      ██ ███████ ██   ██ ███████  -->
<html>
  <head>
    <!-- UTF-8 because we are French ! -->
    <meta charset="utf-8">
    <!-- wicked_pdf helpers -->
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
  </head>
  <body>
    <!-- Menu de la semaine -->
    <div class="container">
      <div class="plan-randomizer">
        <div class="row">
          <h1>RandoMeal</h1>
          <h2>Le menu de votre semaine</h2>
          <% days = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi'] %>
          <% @recipes.each_with_index do |recipe, index| %>
          <div class="col-12 col-md">
            <div class="menu-export">
              <p>-------------------------  ʕ•ᴥ•ʔ  ------------------------------</p>
              <h3><%= days[index] %> : <%= recipe.name %></h3>
              <span class="card-recipe--content__prep-time"><p>• Temps de prépration : <%= recipe.prep_duration %> minutes</span></p>
              <span class="card-recipe--content__total-time"><p>• Temps total : <%= recipe.total_duration %> minutes</span></p>
              <span class="card-recipe--content__people"><p>• Pour <%= @nb_persons[index] %> personnes</span></p>
              <span class="card-recipe--content__all-ingredients"><p>• Ingrédients : <%= ingredient_displayer(recipe, @nb_persons[index] ) %></span></p>
            </div>
          </div>
          <% end %>
        </div>
      <!-- PAGE BREAK --><!-- Ne pas supprimer page break, permets la séparation entre page1 et page2 -->
      <!-- Liste de courses -->
      <div class="plan-shopping">
        <h2>Liste des courses</h2>
          <div class="row">
            <div class="col-12 col-md">
              <% @recipes.each_with_index do |recipe, index| %>
                <% recipe.ingredients.each do |ingredient| %>
                  <% quantity = ingredient&.quantity.nil? ? 0 : ingredient.quantity %>
                  <p>• <%= (quantity.fdiv(recipe.people)).round(2) * @nb_persons[index] %> <%= ingredient.name %> </p>
                <% end %>
              <% end %>
            </div>
          </div>
      </div>
      <!-- Footer -->
      <div class="footer">
        <div class="footer--copyright">
          <div class="row">
            <span class="card-footer--content__built"><p style="text-align:center">Mouliné avec ♥ à Lyon par l'équipe <a href="https://www.RandoMeal.xyz">RandoMeal</a><br>
            <span class="card-footer--contact">✉ Contact : <a href="mailto:contact@randomeal.xyz">contact@randomeal.xyz</a><br>
            <span class="card-footer--content__copyright">© 2022-2022 RandoMeal ®</p>
          </div>
        </div>
      </div>
    </div>
  <body>
</div>

app/views/plans/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <%= wicked_pdf_stylesheet_link_tag "pdf" %>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>
  </head>
  <body onload="number_pages">
    <div id="header">
      <%= wicked_pdf_image_tag 'app/assets/images/logo_randomeal.png' %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_card.html.erb
<div class="card-recipe" data-controller="expander" data-expander-target="output" data-recipe-id="<%= recipe.id %>">
  <div class="card-recipe--top">
    <%= image_tag recipe.image, class: "card-recipe--top__img" %>
  </div>

  <div class="card-recipe--content">

    <div class="card-recipe--content__info">
      <%= link_to recipe.url_marmiton, target: :blank, style: 'text-decoration: none;' do %>
        <h3><%= recipe.name %></h3>
      <% end %>
      <span class="card-recipe--content__prep-time"><i class="fas fa-hourglass-end"></i> Prépration : <%= recipe.prep_duration %> minutes</span>
      <span class="card-recipe--content__total-time"><i class="fas fa-utensils"></i> Total : <%= recipe.total_duration %> minutes</span>
    </div>

    <div class="card-recipe--content__ingredients">
      <h4>Ingrédients:</h4>
      <% recipe.ingredients.each do |ingredient| %>
        <div class="card-recipe--content__ingredients-info">
          • <span data-counter-target="quantity" data-quantity="<%= ingredient.quantity %>"><%= ingredient.quantity %></span> <span id="submit"><%= ingredient.name %></span>
        </div>
      <% end %>
    </div>

    <div class="card-recipe--content__actions">
      <div class="incrementer-button" data-counter-target="buttons">
        <a class="btn incrementer" data-action="click->counter#decrease" data-offset="-1">-</a>
        <span id="counter" data-counter-target="input" data-count="1"><%= recipe.people %></span>
        <a class="btn incrementer" data-action="click->counter#increase"  data-offset="1">+</a>
      </div>
    </div>

    <div class="card-recipe--bottom" >
      <div class="card-recipe--bottom__icon">
        <i class="fas fa-chevron-down" data-action="click->expander#expandcard"></i>
      </div>
    </div>

  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer--copyright">
      © 2022-2022 RandoMeal ® - Built with <i class="fas fa-heart"></i> in Lyon
  </div>
</div>